spring.application.name=helpdesk

spring.datasource.url=jdbc:h2:mem:helpdeskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.show-sql=true
spring.h2.console.enabled=true
jwt.secret=${JWT_SECRET:your-very-long-secret-key-that-is-at-least-256-bits-long-for-hmac}
jwt.expiration=86400000

spring.jpa.defer-datasource-initialization=true
